#!/bin/bash

DIR=`pwd`/`dirname $0`;

cd $DIR/..
composer install
cd -

if [ $# -eq 0 ]; then
    args="php $DIR/src"
else
    args=$@
fi

$DIR/../vendor/bin/tester -l $DIR/temp/test.log -s -j 2 -c $DIR/config/php.ini --colors 1 -p $args

